geommer/yabar

Makefile

Added $(DESTDIR) to install rule in Makefile to fix issues with creating a PKGBUILD file for the AUR. Tested building with makepkg and standalone with make.

Added  to install rule in Makefile.

---

src/ya_exec.c

(Fixes #12) Maybe not the most elegant solution, but it doesn't seem possible to tell whether or not horizontal gap was set without rereading the config file.

Fixed #12 - Center bar when width is specified but not horizontal-gap

---

examples/example.config

Not a big change, but if people copy and paste the config, it wouldn't work off the bat.

spelling error in example config file

---

src/ya_exec.c
src/yabar.h

Before, if yabar exited through a signal, it would not signal spawned processes to exit. This pull should fix that.

Fix unterminated persistent scripts

---

src/ya_exec.c
src/yabar.h

Inceased text buffer size from 512 to 4096 which should (hopefully) be enough for any scripts that need it. Fixes #29.

Increased text buffer size

---

src/ya_exec.c

Cleaned up a small bit of code I previously commited by changing the type of pid from `int` to `pid_t`.

Changed type of local pids in block exec functions to pid_t

---

examples/internal1.config
include/yabar.h
src/intern_blks/ya_intern.c

Created a new internal battery block which accesses `/sys/class/power_supply/BAT*/capacity` and `status` to determine percentage and whether it is charging. `internal-option1` is the specific battery (usually BAT0), and `internal-option2` is a string with 5 substrings for 25, 50, 75, 100%, and a charging symbol.
I'm not sure if using 4 different indicators is essential, but since FontAwesome has 4 icons, I thought it could be of use here.

Added internal battery block.

---

src/intern_blks/ya_intern.c

I apologize for creating a small mistake in the battery block; the original addition adds a space after the indicators even if there is no `internal-option2`. This commit makes sure that if one is not using `internal-option2` no extraneous space is added.

Prevents extra space in battery block if not using indicators.

---

README.md
examples/internal1.config
src/intern_blks/ya_intern.c

Changed format string from `%u` (unsigned decimal int) to `%x` (hexadecimal int) to successfully get the color values. Also added examples to the README and config and removed whitespace.

Fixed internal options 2 and 3 for the internal temperature block.

---

src/ya_draw.c

Hi,
xcb_ewmh_get_wm_name_reply frees the reply on return leading a double free if it's again wiped. You can see this in http://www.openenealinux.org/repo/licenses/xcb-util-wm/ewmh.c. Look for xcb_ewmh_get_utf8_strings_reply and note the free on error inside. This just avoids freeing again.
Andrei

Fix segfault for some windows with odd ways of handling titles (steam & spotify)

---

src/intern_blks/ya_intern.c

Fixes segfault, when internal-option1 is not set for internal date block. Use some default strftime format instead.

Fixed segfault when omitting option 1 for internal date block

---

Makefile

The Makefile builds object files in `src/` and `src/intern_blks/`,
however the clean target only deleted object files inside `src/`
Now the `clean` target deletes object files in `src/`, `src/intern_blks/`
and the program itself

Add Missing Cleanup to Makefile

---

src/ya_parse.c

Previously, when compiling with default settings for Debian Packages,
building was impossible (specifically due to `-Werror=format-security`)
```
cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig` -Wdate-time -D_FORTIFY_SOURCE=2
-DVERSION=\"0.4.0-1-g44211c1\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH  -c -o src/ya_parse.o src/ya_parse.c
src/ya_parse.c: In function ‘ya_inherit_blk’:
src/ya_parse.c:116:3: error: format not a string literal and no format arguments [-Werror=format-security]
fprintf(stderr, per);
^
src/ya_parse.c:126:3: error: format not a string literal and no format arguments [-Werror=format-security]
fprintf(stderr, per);
^ …
```

Fix format error warning when compiling

---

README.md

Add `gdk-pixbuf2` as a dependency (introduced by 407992b, partially fixes #89)
and list the AUR packages maintained by @geommer.
Reformat dependencies for Fedora and Debian/Ubuntu as a list
(better readability)

Update dependencies and list AUR packages (partially fixes #89)

---

Makefile

Just like the CFLAGS variable, the LDLIBS variable should be
extensible with environment variables.
This is for example required because Debian packages (should be)
built with special hardening flags:
https://wiki.debian.org/Hardening

Make LD FLags in Makefile extensible

---

README.md

I created a Debian package (currently based of the 0.4.0 tag) for yabar (which also got adopted by Ubuntu), therefore I figured I might as well include links to these packages in the README.
Since I was already at it, I also reformated the 'Installation' section into 'Packages' and 'From Source'.

Add links to Debian / Ubuntu packages

---

Makefile

For various enviroment it is very valuable to have externally
overwriteable versions (such as distribution packaging, where
a maintainer wants to set a specfic version).
Also, not all build enviroments have git available (e.g. Debian),
therefore the expression `$(shell git describe)` would be evaluated
to "" (nothing).

Make VERSION in Makefile externally overwriteable

---

README.md
doc/yabar.1
include/yabar.h

Fix minor spelling mistakes in README.md, doc/yabar.1 and
include/yabar.h

Fix minor spelling errors

---

README.md
doc/yabar.1
examples/internal1.config
src/intern_blks/ya_intern.c

Add the possibility to set the internal-option1 of the bandwidth block to "default". The bandwidth will then be calculated for the interface used to reach the default gateway (default route 0.0.0.0/0).

Bandwidth blk : 'default' option1

---

README.md
src/ya_exec.c

Add two new environment variables to button commands:
```
${YABAR_CLICK_X} #Click x position
${YABAR_CLICK_Y} #Click y position
```
They represent the relative x and y coordinates of the click in the block (top-left corner).
This should help scripts, which need the know the exact position of the click, like an i3 workspace switcher.

add env variables for click position in block

---

src/intern_blks/ya_intern.c

DRY -- don't repeat yourself. Much code was repeated,
mostly error control. Also used ferror instead of checking
return code from fscanf. Resulting code is cleaner and shorter.

Refactored same code in ya_intern.c

---

src/intern_blks/ya_intern.c

This is regarding one of the warnings that both `gcc` and `clang` report:
```
cc -std=c99 -Iinclude -pedantic -Werror -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0 alsa` -DVERSION=\"0.4.0-147-gce1dea3\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH -DYA_BSPWM  -c -o src/intern_blks/ya_intern.o src/intern_blks/ya_intern.c
src/intern_blks/ya_intern.c:756:19: error: duplicate ‘const’ declaration specifier [-Werror=duplicate-decl-specifier]
static const char const symbols[5] = {0, 'K', 'M', 'G', 'T'};
^~~~~
```

Remove duplicate const declaration.

---

Makefile

I am not sure about the reason to optimizing for size. I think better would be to optimize for speed with LTO enabled. 
If there's a reason for size optimization then, using LTO will improve that as well. Tested with both `clang` and `gcc`.

Move to optimizing for speed with LTO.

---

src/intern_blks/ya_intern.c

The charge string and battery string are preferably unicode symbols
that clash with the actual battery status. A space between them
makes the battery status information more readable.

Append emptystring after charge/battery string

---

.travis.yml
Makefile
doc/yabar.1.asciidoc
examples/example.config
include/yabar.h
shell.nix
src/intern_blks/ya_intern.c

Provides simple support for playerctl and adds a `shell.nix` to make development on NixOS easier.

Integrate `playerctl` into the bar

---

src/ya_exec.c

I'm a member of the Pinguem.ru competition on finding errors in open source projects. Errors, found using PVS-Studio:
yabar/src/ya_exec.c 21      err     V590 Consider inspecting the '* cur != '\\0' && * cur == ' '' expression. The expression is excessive or contains a misprint.

Fixed missprint

---

README.md

Yabar is available in NixOS since 2016 (see https://github.com/NixOS/nixpkgs/commit/093c42161fe2f6730c1379c45bbd990de887284f#diff-f66c765a8c3d400246d177ff137b880f)

Document NixOS support

---

doc/yabar.1.asciidoc
src/intern_blks/ya_intern.c

It's now possible to declare which properties from `playerctl`
(supported are `album`, `artist`, `title`) should be shown in the song
indicator. Before this, the usage of `<artist> - <title>` was hard-coded
which wasn't that usable if artist and/or title were quite long, now
it's up to the user what he wants to see.
The configuration can be used like this:
```
bar-list = ["bar"];
bar: {
position: "top";
block-list: ["ya_song"];
ya_song: {
exec: "YABAR_SONG";
internal-option1: "spotify";
internal-option3: "title artist album";
}
}
```

ya_int_song: improve configuration of playerctl properties

---

doc/yabar.1.asciidoc

Note that using alternative unicode spacing characters will allow for spaces in workspace names

Tip for spaces in workspace labels
